feat: allow renaming columns of duckdb
mlr-org/mlr3db pull request #26
Opened 2022-08-22 12:40 UTC by sebffischer

We rename by creating a new view from the given table / view with renamed columns + update the `self$table` and `self$primary_key` fields. Maybe it is a little inconsistent to not have this for the other data backends. Should I do this as well?

Can we somehow avoid that this function is called on a backend that is part of a task?

2022-08-22 12:43 UTC, mllg commented
> Can we somehow avoid that this function is called on a backend that is part of a task?

We usually treat backends read-only. You could ensure this by making the new column names an argument of the constructor.

2022-08-22 13:12 UTC, sebffischer commented
I think it is fine. I mean it is documented that one should not do it.

2022-08-22 13:14 UTC, sebffischer commented
Maybe it is a little weird, that `Task$rename()` does not call `backend$rename()`. 
Maybe it should try doing so and if it is not available revert to `DataBackendRename` ?

2022-09-15 09:15 UTC, sebffischer commented
@mllg ?

2022-09-23 18:12 UTC, sebffischer commented
@mllg

2022-09-23 23:57 UTC, sebffischer commented
this also fixes the bug that the `...` was not passed on to the duckdb constructor

2022-09-28 12:33 UTC, sebffischer commented on R/DataBackendDuckDB.R
> +      existing_tables = DBI::dbGetQuery(private$.data, "PRAGMA show_tables")$name
comment what is done here

2022-09-28 12:34 UTC, mllg requested changes

2022-09-28 12:34 UTC, mllg commented on R/DataBackendDuckDB.R
> +        private$.rename()
should not be a function, only called once.

2022-09-28 12:34 UTC, mllg commented on R/DataBackendDuckDB.R
> +      table_new = make.unique(c(existing_tables, self$table), sep = "_")[length(existing_tables) + 1L]
add a comment

2022-09-28 12:34 UTC, mllg commented on R/DataBackendDuckDB.R
> +      primary_key_new = new[old == self$primary_key]
only used in l. 290

2022-09-28 12:34 UTC, mllg commented on tests/testthat/test_duckdb.R
> +  expect_true(brn$colnames[1L] == "Sepal.Length")
add some more tests!

2023-10-17 07:15 UTC, closed without merging